name: Build and publish Docker image

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: nesis
      branch:
        description: 'Branch'
        required: true
        default: main
      tag:
        description: 'Tag'
        required: true
        default: latest

jobs:
  push_to_registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ametnes/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: 16
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ametnes/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}

